LIB=	rio
SHLIB_MAJOR= 0

SRCS=	rio.c
INCS=	librio.h
#MAN+=	rio.3

CFLAGS+= -I${.CURDIR} \
	 -I/home/ryan/ck/include \
	 -I/home/ryan/ck/include/x86_64

# TODO: manpages
#MLINKS=	rio.3 rio_create.3

.include <bsd.lib.mk>
